[package]
name = "polms_jpeg"
version = "0.1.0"
authors = ["Robin Moalic <robin.moalic@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
crc32fast = "1.3.0"
inflate = "0.4.5"